name: anchor
dependencies:
- coverage=4.0.3=py35_0
- cycler=0.10.0=py35_0
- flake8=2.5.1=py35_0
- freetype=2.5.5=0
- libpng=1.6.17=0
- matplotlib=1.5.1=np111py35_0
- mccabe=0.3.1=py35_0
- mkl=11.3.1=0
- numpy=1.11.0=py35_0
- openssl=1.0.2g=0
- pandas=0.18.0=np111py35_0
- pep8=1.7.0=py35_0
- pip=8.1.1=py35_1
- py=1.4.31=py35_0
- pyflakes=1.1.0=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- pytest=2.9.1=py35_0
- python=3.5.1=0
- python-dateutil=2.5.2=py35_0
- pytz=2016.3=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np111py35_0
- seaborn=0.7.0=py35_0
- setuptools=20.6.7=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=1
- pip:
  - python-coveralls==2.7.0
  - pyyaml==3.11
  - requests==2.9.1
  - sh==1.11

